### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by hungchinchang** [ajayrathore/krak#2]
Hi Ajay,

I am a kdb developer using kafka and am interested in using the your library for kafka-avro.

I am currently using the kx official kafka thin wrapper functions and trying to embed your stuff in.

I can see you have created a "decode" function which is very useful for decoding the avro messages from kafka in kdb.

Is there a function you can also expose e.g. "encode" so i can potentially use the official kx publish function as well?

I get the current build error

   Compiling krak v0.1.0 (/home/nion/krak-master)
error[E0308]: mismatched types
  --> src/encoder.rs:65:38
   |
65 |         let encoded = encoder.encode(record.to_vec(), &value_strategy);
   |                                      ^^^^^^^^^^^^^^^ expected enum `avro_rs::types::Value`, found a different enum `avro_rs::types::Value`
   |
   = note: expected struct `std::vec::Vec<(&'static str, avro_rs::types::Value)>`
              found struct `std::vec::Vec<(&str, avro_rs::types::Value)>`
   = note: perhaps two different versions of crate `avro_rs` are being used?

error[E0308]: mismatched types
  --> src/receiver.rs:86:9
   |
85 |     match payload {
   |           ------- this expression has type `avro_rs::types::Value`
86 |         Value::Record(mut v) => {
   |         ^^^^^^^^^^^^^^^^^^^^ expected enum `avro_rs::types::Value`, found a different enum `avro_rs::types::Value`
   |
   = note: perhaps two different versions of crate `avro_rs` are being used?

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `krak`.

To learn more, run the command again with --verbose.

Thanks for looking into it.

Nion

**Comment by ajayrathore** [comment]
Hi Nion,

I am really glad that you are trying this library.

1) This error is related to krak depending on a particual version of avro-rs (0.7), this was needed due to certain limitations in avro-rs.
So run the following command before cargo build

```
cargo update -p avro-rs:0.9.0 --precise 0.7.0
```

2) There is already a function exposed called 'encode_table', albeit not documented, you can invoke like this
```
encode_table["trades"; t; `int$count t; string cols t] // 4 params - topic, table, row count, cols
```
I will add this to the documentation.

Let me know if you encounter any other issues.

Cheers,
-Ajay

**Comment by hungchinchang** [comment]
Thanks Ajay,

I few issues i have encountered:

1. cargo building warning:
warning: `extern` fn uses type `std::vec::Vec<std::vec::Vec<u8>>`, which is not FFI-safe
 --> src/encoder.rs:9:103
  |
9 | pub extern "C" fn encode_table(topic: *const K, tbl: *const K, rows: *const K, colnames: *const K) -> Vec<Vec<u8>> {
  |                                                                                                       ^^^^^^^^^^^^ not FFI-safe
  |
  = note: `#[warn(improper_ctypes_definitions)]` on by default
  = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
  = note: this struct has unspecified layout

warning: 1 warning emitted

2. I get a error when i run the encode_table function
q)t:([]id:10?100i;sym:string 10?`2;price:10?100f;size:10?100)
q)encode_table["AVRO"; t; `int$count t; string cols t]
Invalid rows
No Table
Sorry, this application or an associated library has encountered a fatal error and will exit.
If known, please email the steps to reproduce this error to tech@kx.com
with a copy of the kdb+ startup banner and the info printed below.
Thank you.
SIGSEGV: Fault address (nil)
q() [0x4850ab]
/lib64/libpthread.so.0(+0x12dc0) [0x7f0dde4ccdc0]
q(r1+0x1) [0x41fa81]
q() [0x47a21a]
q() [0x444ad5]
q() [0x4458ee]
q() [0x44441e]
q() [0x444625]
q() [0x444a75]
q() [0x4458ee]
q() [0x44441e]
q() [0x444625]
q() [0x444a75]
q() [0x4078e3]
q() [0x44046c]
rlwrap: warning: q crashed, killed by SIGSEGV (core dumped).
rlwrap itself has not crashed, but for transparency,
it will now kill itself with the same signal 

Let me know if you need more information .. i have installed confluent on my linux env for testing.

The decode function seems to work fine :)

Thanks,

Nion

**Comment by ajayrathore** [comment]
Hi Nion

1) Can you confirm your rustc version? I am not getting these warnings, see my bash output
```
~/code/Rust/krak(master ✔) cargo --version --verbose                                                  
cargo 1.44.0-nightly (7019b3ed3 2020-03-17)
release: 1.44.0
commit-hash: 7019b3ed3d539db7429d10a343b69be8c426b576
commit-date: 2020-03-17
~/code/Rust/krak(master ✔) 
~/code/Rust/krak(master ✔) cargo build --release && cp target/release/libkrak.dylib ~/q/m64/libkrak.so
    Finished release [optimized + debuginfo] target(s) in 0.13s
~/code/Rust/krak(master ✔) 
```

2) I have now exposed a new **encode** function which should do the conversion for you, you have to make sure that the topic and schema are created in the confluence schema registry before you do the encoding.

```
q)t:([]id:2?100i;sym:string 2?`2;price:2#9999f;size:2?100f)
q)
q)t
id sym  price size    
----------------------
17 "kl" 9999  36.52273
91 "ep" 9999  95.91177
q)
q)encode : `libkrak 2:(`encode;4)
q)decode: `libkrak 2:(`decode;2)
q)
q)x:encode["trade"; t; `int$count t; string cols t]
topic received: trade
Using Schema Registry : http://localhost:8081
encoded bytes : [Byte(List([0, 0, 0, 0, 2, 34, 4, 107, 108, 0, 0, 0, 0, 128, 135, 195, 64, 0, 0, 176, 223, 232, 66, 66, 64])), Byte(List([0, 0, 0, 0, 2, 182, 1, 4, 101, 112, 0, 0, 0, 0, 128, 135, 195, 64, 0, 0, 123, 109, 90, 250, 87, 64]))]
q)
q)x
0x000000000222046b6c000000008087c3400000b0dfe8424240
0x0000000002b601046570000000008087c34000007b6d5afa5740
q)
q)t ~ decode[1b] each x
Key    = "id"
Value  = Int(17)
Key    = "sym"
Value  = String("kl")
Key    = "price"
Value  = Double(9999.0)
Key    = "size"
Value  = Double(36.522731743752956)
Key    = "id"
Value  = Int(91)
Key    = "sym"
Value  = String("ep")
Key    = "price"
Value  = Double(9999.0)
Key    = "size"
Value  = Double(95.9117692662403)
1b
```

My schema registry has the trade schema defined as follows

![image](https://user-images.githubusercontent.com/1130197/86766992-39021100-c043-11ea-96f7-64df1c62be6e.png)

**Comment by hungchinchang** [comment]
Hi Ajay,

here is my rust 

 nion@centos8  ~/krak-master/target/release/examples  cargo --version --verbose                                                                                                                                     ✔  2118  09:44:13 
cargo 1.46.0-nightly (fede83ccf 2020-07-02)
release: 1.46.0
commit-hash: fede83ccf973457de319ba6fa0e36ead454d2e20
commit-date: 2020-07-02

building :

 nion@centos8  ~/krak-master  cargo update -p avro-rs:0.10.0 --precise 0.7.0                                                                                                101 ↵  2239  18:28:05 
    Updating crates.io index
    Removing avro-rs v0.10.0
    Removing heck v0.3.1
    Removing strum v0.18.0
    Removing strum_macros v0.18.0
    Removing typed-builder v0.5.1
    Removing unicode-segmentation v1.6.0
    Removing uuid v0.8.1
    Removing zerocopy v0.3.0
    Removing zerocopy-derive v0.2.0
 nion@centos8  ~/krak-master  cargo build --release && cp target/release/libkrak.dylib ${QHOME}/l64/libkrak.so                                                                  ✔  2240  18:28:10 
   Compiling syn v1.0.33
   Compiling num-bigint v0.2.6
   Compiling num-rational v0.2.4
   Compiling num v0.2.1
   Compiling rkdb v0.4.0
   Compiling synstructure v0.12.4
   Compiling serde_derive v1.0.114
   Compiling failure_derive v0.1.8
   Compiling failure v0.1.8
   Compiling serde v1.0.114
   Compiling serde_json v1.0.56
   Compiling avro-rs v0.7.0
   Compiling schema_registry_converter v2.0.0 (https://github.com/gklijs/schema_registry_converter#082a9c35)
   Compiling krak v0.1.0 (/home/nion/krak-master)
warning: `extern` fn uses type `std::vec::Vec<std::vec::Vec<u8>>`, which is not FFI-safe
  --> src/encoder.rs:21:103
   |
21 | pub extern "C" fn encode_table(topic: *const K, tbl: *const K, rows: *const K, colnames: *const K) -> Vec<Vec<u8>> {
   |                                                                                                       ^^^^^^^^^^^^ not FFI-safe
   |
   = note: `#[warn(improper_ctypes_definitions)]` on by default
   = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
   = note: this struct has unspecified layout

warning: 1 warning emitted

    Finished release [optimized + debuginfo] target(s) in 53.16s
cp: cannot stat 'target/release/libkrak.dylib': No such file or directory

The encode function works 👍  

It is interesting to note that avro currently only allow one schema per topic. Do you perceive updating the library in the future when they allow multiple schema per topic? 

Also, whats the first parameter of decode - 1b/0b? is it possible to suppress the output?

**Comment by ajayrathore** [comment]
>It is interesting to note that avro currently only allow one schema per topic. Do you perceive updating the library in the future when they allow multiple schema per topic?

I have a use-case where I do receive multiple message types from a single topic, and the rust lib can successfully decode those. The message id encoded at the beginning of the message has enough information required for de-serializing.

>Also, whats the first parameter of decode - 1b/0b? is it possible to suppress the output?


That flag tells the lib weather to return any enum field type as int or symbol.

**Comment by hungchinchang** [comment]
Thanks for the clarification, in your use case, are you using AVRO where you define the schema in schema registry ? i thought you can only define one schema per topic.

If you have multiple message type from a single topic, how do you use the "message id" (in the encode) so you can use decode to know? or you add it in in the message and when you decode, you read the message id and determine which schema to put it in? (but how would you encode and decode know which schema to use if there is only one schema?)

Can you provide examples ? is it industry practice to do so?
